### ISSUE TITLE
can not install from pypi

### ISSUE THREAD

**Issue by fangaofeng** [coddingtonbear/python-measurement#35]
Collecting measurement==3.2.0
  Downloading https://mirrors.aliyun.com/pypi/packages/31/fe/c7fee7e60f30bc3853662452b063aa118ca87b68e77897907c2d5f8b31da/measurement-3.2.0.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: 'e:\saleor\saleor-master\venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\fanga\\AppData\\Local\\Temp\\pip-install-7u0p0a9b\\measurement\\setup.py'"'"'; __file__='"'"'C:\\Users\\fanga\\AppData\\Local\\Temp\\pip-install-7u0p0a9b\\measurement\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\fanga\AppData\Local\Temp\pip-install-7u0p0a9b\measurement\pip-egg-info'
         cwd: C:\Users\fanga\AppData\Local\Temp\pip-install-7u0p0a9b\measurement\
    Complete output (83 lines):
    Traceback (most recent call last):
      File "C:\Python\Python37\lib\urllib\request.py", line 1317, in do_open
        encode_chunked=req.has_header('Transfer-encoding'))
      File "C:\Python\Python37\lib\http\client.py", line 1229, in request
        self._send_request(method, url, body, headers, encode_chunked)
      File "C:\Python\Python37\lib\http\client.py", line 1275, in _send_request
        self.endheaders(body, encode_chunked=encode_chunked)
      File "C:\Python\Python37\lib\http\client.py", line 1224, in endheaders
        self._send_output(message_body, encode_chunked=encode_chunked)
      File "C:\Python\Python37\lib\http\client.py", line 1016, in _send_output
        self.send(msg)
      File "C:\Python\Python37\lib\http\client.py", line 956, in send
        self.connect()
      File "C:\Python\Python37\lib\http\client.py", line 1392, in connect
        server_hostname=server_hostname)
      File "C:\Python\Python37\lib\ssl.py", line 412, in wrap_socket
        session=session
      File "C:\Python\Python37\lib\ssl.py", line 853, in _create
        self.do_handshake()
      File "C:\Python\Python37\lib\ssl.py", line 1117, in do_handshake
        self._sslobj.do_handshake()
    socket.timeout: _ssl.c:1039: The handshake operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 766, in open_url
        return open_with_auth(url, self.opener)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 961, in _socket_timeout
        return func(*args, **kwargs)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 1079, in open_with_auth
        fp = opener(request)
      File "C:\Python\Python37\lib\urllib\request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "C:\Python\Python37\lib\urllib\request.py", line 525, in open
        response = self._open(req, data)
      File "C:\Python\Python37\lib\urllib\request.py", line 543, in _open
        '_open', req)
      File "C:\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
        result = func(*args)
      File "C:\Python\Python37\lib\urllib\request.py", line 1360, in https_open
        context=self._context, check_hostname=self._check_hostname)
      File "C:\Python\Python37\lib\urllib\request.py", line 1319, in do_open
        raise URLError(err)
    urllib.error.URLError: <urlopen error _ssl.c:1039: The handshake operation timed out>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\fanga\AppData\Local\Temp\pip-install-7u0p0a9b\measurement\setup.py", line 4, in <module>
        setup(use_scm_version=True)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "e:\saleor\saleor-master\venv\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "e:\saleor\saleor-master\venv\lib\site-packages\pkg_resources\__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
        return installer(requirement)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\command\easy_install.py", line 667, in easy_install
        not self.always_copy, self.local_index
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 655, in fetch_distribution
        dist = find(requirement)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 635, in find
        loc = self.download(dist.location, tmpdir)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 579, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 824, in _download_url
        return self._attempt_download(url, filename)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 830, in _attempt_download
        headers = self._download_to(url, filename)
      File "e:\saleor\saleor-master\venv\lib\site-packages\setuptools\package_index.py", line 729, in _download_to
        fp = self.open_url(url)
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/16/c1/1c8016475cb612a64ce613c6b61c16224fe6dcfd9527792016ce611c231c/Sphinx-2.4.4-py3-none-any.whl#sha256=fc312670b56cb54920d6cc2ced455a22a547910de10b3142276495ced49231cb: _ssl.c:1039: The handshake operation timed out
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
I change follows，but not install.
pip install --no-cache -I measurement==3.2.0 -i  https://pypi.python.org/pypi
pip install --no-cache -I measurement==3.1.0 -i  https://pypi.python.org/pypi

**Comment by fangaofeng** [comment]
i pip install setup.cfg, then can install. Why need setuptools_scm,sphinx, pytest-runner?
install_requires =
    sympy>=0.7.3
setup_requires =
    setuptools_scm
    sphinx
    pytest-runner

**Comment by codingjoe** [comment]
Hi @fangaofeng,

thanks for reaching out. Based on the error stack trace you provided, it looks like you had a TCP error. In other words, your Internet connection might be the problem. It has Problems downloading Sphinx. Can you install Sphinx manually?

I would recommend to just try again, but let me know if you continue to have problems.

Best
-Joe

**Comment by fangaofeng** [comment]
I’m sure tcp is ok for using mirror of pypi. i install manually 
setuptools_scm,
sphinx,
pytest-runne, and then can install.

**Comment by codingjoe** [comment]
Ok, happy to hear it's working for you. Best Joe
