### ISSUE TITLE
install package error

### ISSUE THREAD

**Issue by dxrvip** [coddingtonbear/python-measurement#70]
pip3 install measurement
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting measurement
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/31/fe/c7fee7e60f30bc3853662452b063aa118ca87b68e77897907c2d5f8b31da/measurement-3.2.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Collecting sympy>=0.7.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d0/04/66be21ceb305c66a4b326b0ae44cc4f027a43bc08cac204b48fb45bb3653/sympy-1.10.1-py3-none-any.whl (6.4 MB)
Collecting mpmath>=0.19
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d4/cf/3965bddbb4f1a61c49aacae0e78fd1fe36b5dc36c797b31f30cf07dcbbb7/mpmath-1.2.1-py3-none-any.whl (532 kB)
Building wheels for collected packages: measurement
  Building wheel for measurement (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1068, in obtain
          return installer(requirement)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/.eggs/MarkupSafe-2.1.1-py3.8-macosx-10.14-arm64.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for measurement
  Running setup.py clean for measurement
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1068, in obtain
          return installer(requirement)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/.eggs/MarkupSafe-2.1.1-py3.8-macosx-10.14-arm64.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for measurement
Failed to build measurement
Installing collected packages: mpmath, sympy, measurement
  WARNING: The script isympy is installed in '/Users/dengxiangren/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py install for measurement ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for measurement did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      /Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 812, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 771, in resolve
          dist = best[req.key] = env.best_match(
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1056, in best_match
          return self.obtain(req, installer)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/pkg_resources/__init__.py", line 1068, in obtain
          return installer(requirement)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/dist.py", line 883, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 95, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 103, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Users/dengxiangren/Library/Python/3.8/lib/python/site-packages/setuptools/wheel.py", line 124, in _convert_metadata
          os.mkdir(destination_eggdir)
      FileExistsError: [Errno 17] File exists: '/private/var/folders/bp/8dq9jh2x653gwbr2s6pprpz40000gn/T/pip-install-7dc_xkkb/measurement_dcb67d412db1462da910f20ee1a7fd14/.eggs/MarkupSafe-2.1.1-py3.8-macosx-10.14-arm64.egg'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> measurement

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
dengxiangren@dengxiangrendeMac-mini saleor %

**Comment by codingjoe** [comment]
Hi @dxrvip,

thanks for reaching out. This is an issue with sphinx, which we do include in the setup requirements. That is probably something that we should change, since the use of `setup.py` is discouraged with the rise of `pyproject.yml`.

Best Joe

**Comment by qwarkys** [comment]
I'm also getting install errors on 3.11b3.  In case this adds new information, here's some pip output:

C:\temp>pip install measurement
Collecting measurement
  Using cached measurement-3.2.0.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [80 lines of output]
      WARNING: The wheel package is not available.
[repeats many times, edited out]

      error: subprocess-exited-with-error

        python setup.py bdist_wheel did not run successfully.
        exit code: 1

        [6 lines of output]
        usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
           or: setup.py --help [cmd1 cmd2 ...]
           or: setup.py --help-commands
           or: setup.py cmd --help

        error: invalid command 'bdist_wheel'
        [end of output]

**Comment by qwarkys** [comment]
Install failed on 3.11b3.  I was able to get it by copying the measurement and measurement egg-info directories from 3.10. I can post the pip report if that helps.

**Comment by amotl** [comment]
Hi there,

on our end, it looks like this:

```console
racker --verbose run --rm --platform=windows/amd64 python:3.9-windowsservercore -- pip install wetterdienst
```

```python
Collecting measurement<4.0,>=3.2
  Downloading measurement-3.2.0.tar.gz (12 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\ContainerAdministrator\AppData\Local\Temp\pip-install-4n5faa8m\measurement_025b7dbbe1da4059871522586272b150\setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "C:\Python\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        [...]
        File "C:\Python\lib\site-packages\setuptools\wheel.py", line 125, in _convert_metadata
          zf.extractall(destination_eggdir)
        File "C:\Python\lib\zipfile.py", line 1642, in extractall
          self._extract_member(zipinfo, path, pwd)
        File "C:\Python\lib\zipfile.py", line 1696, in _extract_member
          open(targetpath, "wb") as target:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\pip-install-4n5faa8m\\measurement_025b7dbbe1da4059871522586272b150\\.eggs\\sphinxcontrib_serializinghtml-1.1.5-py3.9.egg\\sphinxcontrib\\serializinghtml\\locales\\sr@latin\\LC_MESSAGES\\sphinxcontrib.serializinghtml.mo'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

We just submitted #72 to improve the situation. However we haven't tested the patch yet. Running the CI jobs would need one of the project maintainers to approve it.

Thank you in advance and with kind regards,
Andreas.

**Comment by ib250** [comment]
Hi All, is this issue being worked on now?

**Comment by amotl** [comment]
GH-72 and GH-76 are corresponding patches. The patched packages can be _manually_ installed from the Git repository like that:

```
pip install git+https://github.com/syphar/python-measurement@no-sphinx-in-prod
```
```
pip install git+https://github.com/earthobservations/python-measurement@improve-requirements
```

**Comment by codingjoe** [comment]
Hi there, the issues was fixed in v3.2.1 or the latest v4 alpha.
